num=int(input('enter the number:'))
def generate_table(number):
    print(1*number)
    print(2*number)
    print(3*number)
    print(4*number)
    print(5*number)
    print(6*number)
    print(7*number)
    print(8*number)
    print(9*number)
generate_table(num)